### ISSUE TITLE
Bar not loading correctly

### ISSUE THREAD

**Issue by Ciante79** [Pr3vention/UniversalBar#5]
In the latest version:

(This is the bar 4, I haven't tested  on other bars)

![WoWScrnShot_080724_134212](https://github.com/user-attachments/assets/5cd5ada1-aa53-49fc-b41f-150bb0aa360e)

**Comment by Pr3vention** [comment]
At first glance, I suspect this is caused by an unsupported action type, but seeing Beacon to the Beyond not load correctly while another action takes it place in the Beacon's slot has me a bit puzzled. Starting to wonder if some action bar slot IDs changed at some point. Can you provide me with your saved variables file for this addon? You can find it in the WTF folder (from your game install directory, go to _\_retail\_\WTF\Account\MYACCOUNTNAME\SavedVariables_).

**Comment by Ciante79** [comment]
[UniversalBar.lua.txt](https://github.com/user-attachments/files/16571836/UniversalBar.lua.txt)

**Comment by Pr3vention** [comment]
Everything looks good in your config. The action type is correct and all the IDs are valid, so I'm thinking this is a timing issue between the toy box API's availability and the addon's load step. I've added an extra event listener for the toybox that should guarantee better timing, so be on the lookout for another update very soon.

**Comment by Pr3vention** [comment]
Version 1.1.5 should be available now, so please update and let me know if you've seen any improvement. Since your config doesn't use auto-saving when action slot changes occur, you should be able to drag some items off the bar and use the "load bars" button to repopulate them and verify the slots are loading right. If they are, take some off your action bar, log out, then log back in and they should also repopulate as expected.

**Comment by Ciante79** [comment]
Now it works flawlessy, thanks!
